
reference:
  chromosomes: ['20', '21']
  include_nonchromosomal: False

simulation:
  read_length: 100
  fragment_mean: 300
  fragment_stddev: 30
  coverage: 10
  coverage_fraction: 0.25
  num_inserted: 0
  homology: 3

  adjacent_length: 1000
  breakpoints_seed: 100
  dwgsim_seed: 100
  num_breakpoints: 10000
  num_concordant: 100000

